POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "teste",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/ab50fde3-7b6f-4b78-bd33-ac4de007f7f8/attendees
Content-Type: application/json

{
    "name": "Luiz Antonio",
    "email": "luizantmarquesjr@gmail.com"
}

###

GET http://localhost:3333/events/ab50fde3-7b6f-4b78-bd33-ac4de007f7f8

###

GET http://localhost:3333/attendees/1/badge